name: Build Workflow

on:
  push:
#    branches: master

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller qwiklab_badge_checker.spec
      - uses: actions/upload-artifact@v2
        with:
          name: Windows_qwiklabs
          path: dist/qwiklabs-checkerv1.exe